spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: false
    open-in-view: false
    ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web: debug

