server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL
  mvc:
    view:
      suffix: .html

logging:
  level:
    root: debug
    web: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web: debug
