drop table if exists board cascade;
drop table if exists comment cascade;
drop table if exists member cascade;

create table board (
    created_date timestamp(6) not null,
    deleted_date timestamp(6),
    id bigint generated by default as identity,
    updated_date timestamp(6),
    content varchar(4000) not null,
    member_id varchar(255),
    status varchar(255) check (status in ('ACTIVE','SOFT_DELETED')),
    primary key (id)
);

create table comment (
    board_id bigint,
    created_date timestamp(6) not null,
    deleted_date timestamp(6),
    id bigint generated by default as identity,
    updated_date timestamp(6),
    content varchar(4000) not null,
    member_id varchar(255),
    status varchar(255) check (status in ('ACTIVE','SOFT_DELETED')),
    primary key (id)
);

create table member (
    created_date timestamp(6) not null,
    deleted_date timestamp(6),
    updated_date timestamp(6),
    phone_number varchar(11) not null,
    password varchar(24) not null,
    email varchar(255) not null unique,
    id varchar(255) not null,
    nickname varchar(255) not null unique,
    status varchar(255) check (status in ('ACTIVE','SOFT_DELETED')),
    primary key (id)
);

alter table if exists board
   add constraint fk_board_member_member_id
   foreign key (member_id)
   references member;

alter table if exists comment
   add constraint fk_comment_board_board_id
   foreign key (board_id)
   references board;

alter table if exists comment
   add constraint fk_comment_member_member_id
   foreign key (member_id)
   references member;